In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset=pd.read_csv("/content/drive/My Drive/Colab Notebooks/forestfires.csv", header=0, sep=";")

In [ ]:
headernames = ['X','Y','month','day','FFMC','DMC','DC','ISI','temp','RH','wind','rain','area'] 

In [ ]:
dataset=pd.read_csv("/content/drive/My Drive/Colab Notebooks/forestfires.csv")
dataset.head()

X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [ ]:

dataset

X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

[517 rows x 13 columns]

In [ ]:
y = dataset['area']
X = dataset.drop('area', axis=1)
X = X.drop('month', axis=1)
X = X.drop('day', axis=1)


i = len(X.columns)
X = X.drop(X.columns[i-1], axis=1)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.40)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
lab_enc = preprocessing.LabelEncoder()
y_train_encoded = lab_enc.fit_transform(y_train)
print(y_train_encoded)
print(utils.multiclass.type_of_target(y_train))
print(utils.multiclass.type_of_target(y_train.astype('int')))
print(utils.multiclass.type_of_target(y_train_encoded))

[ 39 152   0   0  87 117   0   0  31   0  97   0   0  76 154  56  59 145
  89  34 102   0  62  18 118   0 137  27  27   0  28  82 111   0   0   0
   0 112   0   0   0   0   0  52   0   0   0   0   0  50   0   0   0  81
   0   0  11   0   0   0 107  36   0  33   0   0   0 151   0 124   0  94
   0   0   9 136 130   0 125 126 104 128 101 150   0 157   0   0  55   0
   0   0   0 148   0  99   5   0   0   0 147  17  49   0  83 120 155  22
   0   0  90   0   0 110  57 106 105  16 156   0  26 140  66 153   0  85
 132  80  10  95  12   0   0   0 113 123 142 160   0   0 141  77 127  75
   0  79   0   0   0 108  40 115   0  53   0  45   1   0   0   0 103   0
   6  23  98   0  29  47   0 129  70  21   0 131   0  46   3  41   0   0
   0 119  15 116   0   0   0   0  88   0  67  69  48   0   0   0   0  58
  32   0   0   6 109 133   0   0   0   0 138  24   0   0  78   0   0  25
   0  32   0  30   0   0 135   0   0 134  13   0   0  26   0   7 143   0
   0  20 122  44   0  61 121 114 146  86   4  96   

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 8)
classifier.fit(X_train, y_train_encoded)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=8, p=2,
                     weights='uniform')

In [ ]:
y_pred = classifier.predict(X_test)


In [ ]:
lab_enc = preprocessing.LabelEncoder()
y_test_encoded = lab_enc.fit_transform(y_test)
print(y_test_encoded)
print(utils.multiclass.type_of_target(y_test))
print(utils.multiclass.type_of_target(y_test.astype('int')))
print(utils.multiclass.type_of_target(y_test_encoded))


[ 0  0 18  0  1  0 45  0  5 98 65  0  0  0  0 49  0 32 15 72 21  0  0 17
  0  0  9 27  4 35 51 94  0  0 71  0  0 89  0 29  0  0  0 25 62  0  0 84
  0  0  0  0  0 30  0  0  0  0  0 56  0 80 91 96  0 54  0  0  0 92  0 53
 44 13  0  0  0 81 16 10  0  0  0  0 57 97 78  0 73  0  0 74  7  0 22  0
 28 14  6 40  0  0  0 83 50 58 24  0  0 41  0 38  0  0  0  0 67  0  0 63
 88 93  0  0 61 87 26  0  0  0 85  0  0  0  0 11 26  0  0 20  0 70 66 48
  0 82  0 59  0 43 39  0 79  3 19  0  0  0  0  0  0 36  0  0 52 23  0  0
 55  0 42  0  0  0 90 64 60  2  0 47  0 76 11  0  0  8  0  0  0  0  0  0
 77  0 75 69 31 37 46  0 95 99 12 33 68 34 86]
continuous
multiclass
multiclass


In [ ]:


from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test_encoded, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test_encoded, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test_encoded,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[106   0   0 ...   0   0   0]
 [  1   0   0 ...   0   0   0]
 [  1   0   0 ...   0   0   0]
 ...
 [  1   0   0 ...   0   0   0]
 [  1   0   0 ...   0   0   0]
 [  1   0   0 ...   0   0   0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.51      1.00      0.68       106
           1       0.00      0.00      0.00         1
           2       0.00      0.00      0.00         1
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1
           8       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         1
          10       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         2
          12       0.00      0.00      0.00         1
          

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
